### PR TITLE
update lein-fregec version

### PR DESCRIPTION
**Pull request by swr1bm86**
work with latest lein-fregec

### CODE REVIEW

**Comment by seancorfield** [comment]
:+1: The Leiningen plugin itself also needs updating to use the latest Frege version I believe? Then the template will need updating again. And then I'll need to publish both to Clojars again.

**Comment by swr1bm86** [comment]
cool :smile:

**Comment by seancorfield** [comment]
That's all done. Posted the new versions!

**Comment by swr1bm86** [comment]
yeah i just updated it.

and what is your idea about this #1

**Comment by seancorfield** [comment]
I haven't decided yet (which is why it's still open :) ).

**Pull request merged**
